// Code generated by protoc-gen-go.
// source: protos/golang.conradwood.net/apis/goproxy/goproxy.proto
// DO NOT EDIT!

/*
Package goproxy is a generated protocol buffer package.

It is generated from these files:
	protos/golang.conradwood.net/apis/goproxy/goproxy.proto

It has these top-level messages:
	CachedModule
	ModuleInfoRequest
	ModuleInfo
	VersionInfo
	GetPathRequest
	BinData
*/
package goproxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "golang.conradwood.net/apis/common"
import h2gproxy "golang.conradwood.net/apis/h2gproxy"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MODULETYPE int32

const (
	MODULETYPE_UNKNOWN        MODULETYPE = 0
	MODULETYPE_PROTO          MODULETYPE = 2
	MODULETYPE_LOCALMODULE    MODULETYPE = 3
	MODULETYPE_EXTERNALMODULE MODULETYPE = 4
)

var MODULETYPE_name = map[int32]string{
	0: "UNKNOWN",
	2: "PROTO",
	3: "LOCALMODULE",
	4: "EXTERNALMODULE",
}
var MODULETYPE_value = map[string]int32{
	"UNKNOWN":        0,
	"PROTO":          2,
	"LOCALMODULE":    3,
	"EXTERNALMODULE": 4,
}

func (x MODULETYPE) String() string {
	return proto.EnumName(MODULETYPE_name, int32(x))
}
func (MODULETYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CachedModule struct {
	ID          uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Path        string `protobuf:"bytes,2,opt,name=Path" json:"Path,omitempty"`
	Version     string `protobuf:"bytes,3,opt,name=Version" json:"Version,omitempty"`
	Suffix      string `protobuf:"bytes,4,opt,name=Suffix" json:"Suffix,omitempty"`
	Key         string `protobuf:"bytes,5,opt,name=Key" json:"Key,omitempty"`
	Created     uint32 `protobuf:"varint,6,opt,name=Created" json:"Created,omitempty"`
	LastUsed    uint32 `protobuf:"varint,7,opt,name=LastUsed" json:"LastUsed,omitempty"`
	ToBeDeleted bool   `protobuf:"varint,8,opt,name=ToBeDeleted" json:"ToBeDeleted,omitempty"`
}

func (m *CachedModule) Reset()                    { *m = CachedModule{} }
func (m *CachedModule) String() string            { return proto.CompactTextString(m) }
func (*CachedModule) ProtoMessage()               {}
func (*CachedModule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CachedModule) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *CachedModule) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CachedModule) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CachedModule) GetSuffix() string {
	if m != nil {
		return m.Suffix
	}
	return ""
}

func (m *CachedModule) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CachedModule) GetCreated() uint32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CachedModule) GetLastUsed() uint32 {
	if m != nil {
		return m.LastUsed
	}
	return 0
}

func (m *CachedModule) GetToBeDeleted() bool {
	if m != nil {
		return m.ToBeDeleted
	}
	return false
}

type ModuleInfoRequest struct {
	URL string `protobuf:"bytes,1,opt,name=URL" json:"URL,omitempty"`
}

func (m *ModuleInfoRequest) Reset()                    { *m = ModuleInfoRequest{} }
func (m *ModuleInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*ModuleInfoRequest) ProtoMessage()               {}
func (*ModuleInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ModuleInfoRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type ModuleInfo struct {
	ModuleType MODULETYPE `protobuf:"varint,1,opt,name=ModuleType,enum=goproxy.MODULETYPE" json:"ModuleType,omitempty"`
	Exists     bool       `protobuf:"varint,2,opt,name=Exists" json:"Exists,omitempty"`
}

func (m *ModuleInfo) Reset()                    { *m = ModuleInfo{} }
func (m *ModuleInfo) String() string            { return proto.CompactTextString(m) }
func (*ModuleInfo) ProtoMessage()               {}
func (*ModuleInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ModuleInfo) GetModuleType() MODULETYPE {
	if m != nil {
		return m.ModuleType
	}
	return MODULETYPE_UNKNOWN
}

func (m *ModuleInfo) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type VersionInfo struct {
	Version     uint64 `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	BuildTime   uint32 `protobuf:"varint,2,opt,name=BuildTime" json:"BuildTime,omitempty"`
	VersionName string `protobuf:"bytes,3,opt,name=VersionName" json:"VersionName,omitempty"`
}

func (m *VersionInfo) Reset()                    { *m = VersionInfo{} }
func (m *VersionInfo) String() string            { return proto.CompactTextString(m) }
func (*VersionInfo) ProtoMessage()               {}
func (*VersionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *VersionInfo) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *VersionInfo) GetBuildTime() uint32 {
	if m != nil {
		return m.BuildTime
	}
	return 0
}

func (m *VersionInfo) GetVersionName() string {
	if m != nil {
		return m.VersionName
	}
	return ""
}

type GetPathRequest struct {
	Path string `protobuf:"bytes,1,opt,name=Path" json:"Path,omitempty"`
}

func (m *GetPathRequest) Reset()                    { *m = GetPathRequest{} }
func (m *GetPathRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPathRequest) ProtoMessage()               {}
func (*GetPathRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetPathRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type BinData struct {
	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *BinData) Reset()                    { *m = BinData{} }
func (m *BinData) String() string            { return proto.CompactTextString(m) }
func (*BinData) ProtoMessage()               {}
func (*BinData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BinData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CachedModule)(nil), "goproxy.CachedModule")
	proto.RegisterType((*ModuleInfoRequest)(nil), "goproxy.ModuleInfoRequest")
	proto.RegisterType((*ModuleInfo)(nil), "goproxy.ModuleInfo")
	proto.RegisterType((*VersionInfo)(nil), "goproxy.VersionInfo")
	proto.RegisterType((*GetPathRequest)(nil), "goproxy.GetPathRequest")
	proto.RegisterType((*BinData)(nil), "goproxy.BinData")
	proto.RegisterEnum("goproxy.MODULETYPE", MODULETYPE_name, MODULETYPE_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GoProxy service

type GoProxyClient interface {
	// h2gproxy endpoint
	StreamHTTP(ctx context.Context, in *h2gproxy.StreamRequest, opts ...grpc.CallOption) (GoProxy_StreamHTTPClient, error)
	AnalyseURL(ctx context.Context, in *ModuleInfoRequest, opts ...grpc.CallOption) (*ModuleInfo, error)
	// given a path, will download response
	GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (GoProxy_GetPathClient, error)
}

type goProxyClient struct {
	cc *grpc.ClientConn
}

func NewGoProxyClient(cc *grpc.ClientConn) GoProxyClient {
	return &goProxyClient{cc}
}

func (c *goProxyClient) StreamHTTP(ctx context.Context, in *h2gproxy.StreamRequest, opts ...grpc.CallOption) (GoProxy_StreamHTTPClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GoProxy_serviceDesc.Streams[0], c.cc, "/goproxy.GoProxy/StreamHTTP", opts...)
	if err != nil {
		return nil, err
	}
	x := &goProxyStreamHTTPClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GoProxy_StreamHTTPClient interface {
	Recv() (*h2gproxy.StreamDataResponse, error)
	grpc.ClientStream
}

type goProxyStreamHTTPClient struct {
	grpc.ClientStream
}

func (x *goProxyStreamHTTPClient) Recv() (*h2gproxy.StreamDataResponse, error) {
	m := new(h2gproxy.StreamDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *goProxyClient) AnalyseURL(ctx context.Context, in *ModuleInfoRequest, opts ...grpc.CallOption) (*ModuleInfo, error) {
	out := new(ModuleInfo)
	err := grpc.Invoke(ctx, "/goproxy.GoProxy/AnalyseURL", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goProxyClient) GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (GoProxy_GetPathClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GoProxy_serviceDesc.Streams[1], c.cc, "/goproxy.GoProxy/GetPath", opts...)
	if err != nil {
		return nil, err
	}
	x := &goProxyGetPathClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GoProxy_GetPathClient interface {
	Recv() (*BinData, error)
	grpc.ClientStream
}

type goProxyGetPathClient struct {
	grpc.ClientStream
}

func (x *goProxyGetPathClient) Recv() (*BinData, error) {
	m := new(BinData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GoProxy service

type GoProxyServer interface {
	// h2gproxy endpoint
	StreamHTTP(*h2gproxy.StreamRequest, GoProxy_StreamHTTPServer) error
	AnalyseURL(context.Context, *ModuleInfoRequest) (*ModuleInfo, error)
	// given a path, will download response
	GetPath(*GetPathRequest, GoProxy_GetPathServer) error
}

func RegisterGoProxyServer(s *grpc.Server, srv GoProxyServer) {
	s.RegisterService(&_GoProxy_serviceDesc, srv)
}

func _GoProxy_StreamHTTP_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(h2gproxy.StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoProxyServer).StreamHTTP(m, &goProxyStreamHTTPServer{stream})
}

type GoProxy_StreamHTTPServer interface {
	Send(*h2gproxy.StreamDataResponse) error
	grpc.ServerStream
}

type goProxyStreamHTTPServer struct {
	grpc.ServerStream
}

func (x *goProxyStreamHTTPServer) Send(m *h2gproxy.StreamDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GoProxy_AnalyseURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoProxyServer).AnalyseURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goproxy.GoProxy/AnalyseURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoProxyServer).AnalyseURL(ctx, req.(*ModuleInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoProxy_GetPath_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPathRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoProxyServer).GetPath(m, &goProxyGetPathServer{stream})
}

type GoProxy_GetPathServer interface {
	Send(*BinData) error
	grpc.ServerStream
}

type goProxyGetPathServer struct {
	grpc.ServerStream
}

func (x *goProxyGetPathServer) Send(m *BinData) error {
	return x.ServerStream.SendMsg(m)
}

var _GoProxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goproxy.GoProxy",
	HandlerType: (*GoProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyseURL",
			Handler:    _GoProxy_AnalyseURL_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHTTP",
			Handler:       _GoProxy_StreamHTTP_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPath",
			Handler:       _GoProxy_GetPath_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/golang.conradwood.net/apis/goproxy/goproxy.proto",
}

func init() {
	proto.RegisterFile("protos/golang.conradwood.net/apis/goproxy/goproxy.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xad, 0x81, 0x60, 0x18, 0x12, 0x4a, 0x37, 0x52, 0x63, 0xb9, 0x89, 0x84, 0xac, 0x56, 0x42,
	0x3d, 0x38, 0x11, 0x91, 0xda, 0x53, 0x0f, 0x01, 0xac, 0x14, 0xc5, 0x01, 0xb4, 0x31, 0x6d, 0x73,
	0xdc, 0xe2, 0x01, 0x2c, 0x81, 0x97, 0xda, 0x8b, 0x0a, 0xbf, 0xb0, 0xb7, 0xfe, 0xa6, 0x6a, 0xd7,
	0x1f, 0xb8, 0x51, 0x94, 0xd3, 0xce, 0xbc, 0xf7, 0x66, 0xbd, 0xf3, 0xc6, 0x03, 0x9f, 0x37, 0x11,
	0x17, 0x3c, 0xbe, 0x5c, 0xf0, 0x15, 0x0b, 0x17, 0xf6, 0x8c, 0x87, 0x11, 0xf3, 0x7f, 0x73, 0xee,
	0xdb, 0x21, 0x8a, 0x4b, 0xb6, 0x09, 0x24, 0xb5, 0x89, 0xf8, 0x6e, 0x9f, 0x9d, 0xb6, 0xaa, 0x20,
	0x7a, 0x9a, 0x9a, 0xf6, 0x0b, 0xa5, 0x33, 0xbe, 0x5e, 0xf3, 0x30, 0x3d, 0x92, 0x42, 0xb3, 0xfb,
	0x82, 0x7e, 0xd9, 0x5d, 0x24, 0xdf, 0xca, 0x82, 0xa4, 0xc6, 0xfa, 0xab, 0xc1, 0x71, 0x9f, 0xcd,
	0x96, 0xe8, 0xdf, 0x73, 0x7f, 0xbb, 0x42, 0xd2, 0x84, 0xd2, 0x70, 0x60, 0x68, 0x6d, 0xad, 0x53,
	0xa1, 0xa5, 0xe1, 0x80, 0x10, 0xa8, 0x4c, 0x98, 0x58, 0x1a, 0xa5, 0xb6, 0xd6, 0xa9, 0x53, 0x15,
	0x13, 0x03, 0xf4, 0x6f, 0x18, 0xc5, 0x01, 0x0f, 0x8d, 0xb2, 0x82, 0xb3, 0x94, 0xbc, 0x85, 0xea,
	0xc3, 0x76, 0x3e, 0x0f, 0x76, 0x46, 0x45, 0x11, 0x69, 0x46, 0x5a, 0x50, 0xbe, 0xc3, 0xbd, 0x71,
	0xa4, 0x40, 0x19, 0xca, 0x3b, 0xfa, 0x11, 0x32, 0x81, 0xbe, 0x51, 0x6d, 0x6b, 0x9d, 0x13, 0x9a,
	0xa5, 0xc4, 0x84, 0x9a, 0xcb, 0x62, 0x31, 0x8d, 0xd1, 0x37, 0x74, 0x45, 0xe5, 0x39, 0x69, 0x43,
	0xc3, 0xe3, 0x3d, 0x1c, 0xe0, 0x0a, 0x65, 0x65, 0xad, 0xad, 0x75, 0x6a, 0xb4, 0x08, 0x59, 0x1f,
	0xe0, 0x4d, 0xd2, 0xc9, 0x30, 0x9c, 0x73, 0x8a, 0xbf, 0xb6, 0x18, 0x0b, 0xf9, 0xf9, 0x29, 0x75,
	0x55, 0x57, 0x75, 0x2a, 0x43, 0xeb, 0x11, 0xe0, 0x20, 0x23, 0xd7, 0x59, 0xe6, 0xed, 0x37, 0xa8,
	0x64, 0xcd, 0xee, 0xa9, 0x9d, 0x8d, 0xe5, 0x7e, 0x3c, 0x98, 0xba, 0x8e, 0xf7, 0x38, 0x71, 0x68,
	0x41, 0x26, 0x7b, 0x75, 0x76, 0x41, 0x2c, 0x62, 0xe5, 0x4d, 0x8d, 0xa6, 0x99, 0xb5, 0x80, 0x46,
	0x6a, 0x87, 0xba, 0xbb, 0x60, 0x56, 0xe2, 0x6a, 0x6e, 0xd6, 0x39, 0xd4, 0x7b, 0xdb, 0x60, 0xe5,
	0x7b, 0xc1, 0x1a, 0xd5, 0x1d, 0x27, 0xf4, 0x00, 0xc8, 0x56, 0x53, 0xe1, 0x88, 0xad, 0x31, 0x35,
	0xba, 0x08, 0x59, 0xef, 0xa1, 0x79, 0x8b, 0x42, 0x4e, 0x24, 0xeb, 0x33, 0x1b, 0x96, 0x76, 0x18,
	0x96, 0x75, 0x01, 0x7a, 0x2f, 0x08, 0x07, 0x4c, 0x30, 0x49, 0xcb, 0x53, 0xd1, 0xc7, 0x54, 0xc5,
	0x1f, 0x87, 0x00, 0x87, 0xfe, 0x48, 0x03, 0xf4, 0xe9, 0xe8, 0x6e, 0x34, 0xfe, 0x3e, 0x6a, 0xbd,
	0x22, 0x75, 0x38, 0x9a, 0xd0, 0xb1, 0x37, 0x6e, 0x95, 0xc8, 0x6b, 0x68, 0xb8, 0xe3, 0xfe, 0x8d,
	0x9b, 0x48, 0x5b, 0x65, 0x42, 0xa0, 0xe9, 0xfc, 0xf0, 0x1c, 0x3a, 0xca, 0xb1, 0x4a, 0xf7, 0x8f,
	0x06, 0xfa, 0x2d, 0x9f, 0x48, 0xcf, 0x88, 0x03, 0xf0, 0x20, 0x22, 0x64, 0xeb, 0xaf, 0x9e, 0x37,
	0x21, 0x67, 0x76, 0xfe, 0xdb, 0x25, 0x68, 0xfa, 0x60, 0xf3, 0xfc, 0x29, 0x21, 0xdf, 0x44, 0x31,
	0xde, 0xf0, 0x30, 0xc6, 0x2b, 0x8d, 0x7c, 0x01, 0xb8, 0x09, 0xd9, 0x6a, 0x1f, 0xe3, 0x94, 0xba,
	0xc4, 0x3c, 0x8c, 0xe4, 0xe9, 0x88, 0xcd, 0xd3, 0x67, 0x38, 0xf2, 0x09, 0xf4, 0xd4, 0x21, 0x72,
	0x96, 0xf3, 0xff, 0x7b, 0x66, 0xb6, 0x72, 0x22, 0xb5, 0xe9, 0x4a, 0xeb, 0x5d, 0xc0, 0xbb, 0x10,
	0x45, 0x71, 0x91, 0xe4, 0x12, 0x65, 0xc2, 0x9f, 0x55, 0xb5, 0x3b, 0xd7, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x61, 0x2d, 0xe4, 0x38, 0xe3, 0x03, 0x00, 0x00,
}
