// Code generated by protoc-gen-go.
// source: protos/golang.conradwood.net/apis/goproxy/goproxy.proto
// DO NOT EDIT!

/*
Package goproxy is a generated protocol buffer package.

It is generated from these files:
	protos/golang.conradwood.net/apis/goproxy/goproxy.proto

It has these top-level messages:
	Config
	UpStreamProxy
	ArtefactDef
	CachedModule
	ModuleInfoRequest
	ModuleInfo
	VersionInfo
	GetPathRequest
	BinData
*/
package goproxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "golang.conradwood.net/apis/common"
import h2gproxy "golang.conradwood.net/apis/h2gproxy"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MODULETYPE int32

const (
	MODULETYPE_UNKNOWN        MODULETYPE = 0
	MODULETYPE_PROTO          MODULETYPE = 2
	MODULETYPE_ARTEFACT       MODULETYPE = 3
	MODULETYPE_EXTERNALMODULE MODULETYPE = 4
	MODULETYPE_UPSTREAMPROXY  MODULETYPE = 5
)

var MODULETYPE_name = map[int32]string{
	0: "UNKNOWN",
	2: "PROTO",
	3: "ARTEFACT",
	4: "EXTERNALMODULE",
	5: "UPSTREAMPROXY",
}
var MODULETYPE_value = map[string]int32{
	"UNKNOWN":        0,
	"PROTO":          2,
	"ARTEFACT":       3,
	"EXTERNALMODULE": 4,
	"UPSTREAMPROXY":  5,
}

func (x MODULETYPE) String() string {
	return proto.EnumName(MODULETYPE_name, int32(x))
}
func (MODULETYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Config struct {
	LocalHosts        []string         `protobuf:"bytes,1,rep,name=LocalHosts" json:"LocalHosts,omitempty"`
	ArtefactResolvers []*ArtefactDef   `protobuf:"bytes,2,rep,name=ArtefactResolvers" json:"ArtefactResolvers,omitempty"`
	GoGetProxy        string           `protobuf:"bytes,3,opt,name=GoGetProxy" json:"GoGetProxy,omitempty"`
	GoProxies         []*UpStreamProxy `protobuf:"bytes,4,rep,name=GoProxies" json:"GoProxies,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetLocalHosts() []string {
	if m != nil {
		return m.LocalHosts
	}
	return nil
}

func (m *Config) GetArtefactResolvers() []*ArtefactDef {
	if m != nil {
		return m.ArtefactResolvers
	}
	return nil
}

func (m *Config) GetGoGetProxy() string {
	if m != nil {
		return m.GoGetProxy
	}
	return ""
}

func (m *Config) GetGoProxies() []*UpStreamProxy {
	if m != nil {
		return m.GoProxies
	}
	return nil
}

type UpStreamProxy struct {
	Matcher  string `protobuf:"bytes,1,opt,name=Matcher" json:"Matcher,omitempty"`
	Proxy    string `protobuf:"bytes,2,opt,name=Proxy" json:"Proxy,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=Username" json:"Username,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=Password" json:"Password,omitempty"`
	Token    string `protobuf:"bytes,5,opt,name=Token" json:"Token,omitempty"`
}

func (m *UpStreamProxy) Reset()                    { *m = UpStreamProxy{} }
func (m *UpStreamProxy) String() string            { return proto.CompactTextString(m) }
func (*UpStreamProxy) ProtoMessage()               {}
func (*UpStreamProxy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpStreamProxy) GetMatcher() string {
	if m != nil {
		return m.Matcher
	}
	return ""
}

func (m *UpStreamProxy) GetProxy() string {
	if m != nil {
		return m.Proxy
	}
	return ""
}

func (m *UpStreamProxy) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpStreamProxy) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpStreamProxy) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ArtefactDef struct {
	Path       string `protobuf:"bytes,1,opt,name=Path" json:"Path,omitempty"`
	ArtefactID uint64 `protobuf:"varint,2,opt,name=ArtefactID" json:"ArtefactID,omitempty"`
	Domain     string `protobuf:"bytes,3,opt,name=Domain" json:"Domain,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=Name" json:"Name,omitempty"`
}

func (m *ArtefactDef) Reset()                    { *m = ArtefactDef{} }
func (m *ArtefactDef) String() string            { return proto.CompactTextString(m) }
func (*ArtefactDef) ProtoMessage()               {}
func (*ArtefactDef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ArtefactDef) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ArtefactDef) GetArtefactID() uint64 {
	if m != nil {
		return m.ArtefactID
	}
	return 0
}

func (m *ArtefactDef) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *ArtefactDef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CachedModule struct {
	ID           uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Path         string `protobuf:"bytes,2,opt,name=Path" json:"Path,omitempty"`
	Version      string `protobuf:"bytes,3,opt,name=Version" json:"Version,omitempty"`
	Suffix       string `protobuf:"bytes,4,opt,name=Suffix" json:"Suffix,omitempty"`
	Key          string `protobuf:"bytes,5,opt,name=Key" json:"Key,omitempty"`
	Created      uint32 `protobuf:"varint,6,opt,name=Created" json:"Created,omitempty"`
	LastUsed     uint32 `protobuf:"varint,7,opt,name=LastUsed" json:"LastUsed,omitempty"`
	ToBeDeleted  bool   `protobuf:"varint,8,opt,name=ToBeDeleted" json:"ToBeDeleted,omitempty"`
	FailingSince uint32 `protobuf:"varint,9,opt,name=FailingSince" json:"FailingSince,omitempty"`
	FailCounter  uint32 `protobuf:"varint,10,opt,name=FailCounter" json:"FailCounter,omitempty"`
	LastFailed   uint32 `protobuf:"varint,11,opt,name=LastFailed" json:"LastFailed,omitempty"`
	PutFailed    bool   `protobuf:"varint,12,opt,name=PutFailed" json:"PutFailed,omitempty"`
	PutError     string `protobuf:"bytes,13,opt,name=PutError" json:"PutError,omitempty"`
}

func (m *CachedModule) Reset()                    { *m = CachedModule{} }
func (m *CachedModule) String() string            { return proto.CompactTextString(m) }
func (*CachedModule) ProtoMessage()               {}
func (*CachedModule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CachedModule) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *CachedModule) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CachedModule) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CachedModule) GetSuffix() string {
	if m != nil {
		return m.Suffix
	}
	return ""
}

func (m *CachedModule) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CachedModule) GetCreated() uint32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CachedModule) GetLastUsed() uint32 {
	if m != nil {
		return m.LastUsed
	}
	return 0
}

func (m *CachedModule) GetToBeDeleted() bool {
	if m != nil {
		return m.ToBeDeleted
	}
	return false
}

func (m *CachedModule) GetFailingSince() uint32 {
	if m != nil {
		return m.FailingSince
	}
	return 0
}

func (m *CachedModule) GetFailCounter() uint32 {
	if m != nil {
		return m.FailCounter
	}
	return 0
}

func (m *CachedModule) GetLastFailed() uint32 {
	if m != nil {
		return m.LastFailed
	}
	return 0
}

func (m *CachedModule) GetPutFailed() bool {
	if m != nil {
		return m.PutFailed
	}
	return false
}

func (m *CachedModule) GetPutError() string {
	if m != nil {
		return m.PutError
	}
	return ""
}

type ModuleInfoRequest struct {
	URL string `protobuf:"bytes,1,opt,name=URL" json:"URL,omitempty"`
}

func (m *ModuleInfoRequest) Reset()                    { *m = ModuleInfoRequest{} }
func (m *ModuleInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*ModuleInfoRequest) ProtoMessage()               {}
func (*ModuleInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ModuleInfoRequest) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type ModuleInfo struct {
	ModuleType MODULETYPE `protobuf:"varint,1,opt,name=ModuleType,enum=goproxy.MODULETYPE" json:"ModuleType,omitempty"`
	Exists     bool       `protobuf:"varint,2,opt,name=Exists" json:"Exists,omitempty"`
}

func (m *ModuleInfo) Reset()                    { *m = ModuleInfo{} }
func (m *ModuleInfo) String() string            { return proto.CompactTextString(m) }
func (*ModuleInfo) ProtoMessage()               {}
func (*ModuleInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ModuleInfo) GetModuleType() MODULETYPE {
	if m != nil {
		return m.ModuleType
	}
	return MODULETYPE_UNKNOWN
}

func (m *ModuleInfo) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type VersionInfo struct {
	Version     uint64 `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	BuildTime   uint32 `protobuf:"varint,2,opt,name=BuildTime" json:"BuildTime,omitempty"`
	VersionName string `protobuf:"bytes,3,opt,name=VersionName" json:"VersionName,omitempty"`
}

func (m *VersionInfo) Reset()                    { *m = VersionInfo{} }
func (m *VersionInfo) String() string            { return proto.CompactTextString(m) }
func (*VersionInfo) ProtoMessage()               {}
func (*VersionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *VersionInfo) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *VersionInfo) GetBuildTime() uint32 {
	if m != nil {
		return m.BuildTime
	}
	return 0
}

func (m *VersionInfo) GetVersionName() string {
	if m != nil {
		return m.VersionName
	}
	return ""
}

type GetPathRequest struct {
	Path string `protobuf:"bytes,1,opt,name=Path" json:"Path,omitempty"`
}

func (m *GetPathRequest) Reset()                    { *m = GetPathRequest{} }
func (m *GetPathRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPathRequest) ProtoMessage()               {}
func (*GetPathRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetPathRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type BinData struct {
	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *BinData) Reset()                    { *m = BinData{} }
func (m *BinData) String() string            { return proto.CompactTextString(m) }
func (*BinData) ProtoMessage()               {}
func (*BinData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BinData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "goproxy.Config")
	proto.RegisterType((*UpStreamProxy)(nil), "goproxy.UpStreamProxy")
	proto.RegisterType((*ArtefactDef)(nil), "goproxy.ArtefactDef")
	proto.RegisterType((*CachedModule)(nil), "goproxy.CachedModule")
	proto.RegisterType((*ModuleInfoRequest)(nil), "goproxy.ModuleInfoRequest")
	proto.RegisterType((*ModuleInfo)(nil), "goproxy.ModuleInfo")
	proto.RegisterType((*VersionInfo)(nil), "goproxy.VersionInfo")
	proto.RegisterType((*GetPathRequest)(nil), "goproxy.GetPathRequest")
	proto.RegisterType((*BinData)(nil), "goproxy.BinData")
	proto.RegisterEnum("goproxy.MODULETYPE", MODULETYPE_name, MODULETYPE_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GoProxy service

type GoProxyClient interface {
	// h2gproxy endpoint
	StreamHTTP(ctx context.Context, in *h2gproxy.StreamRequest, opts ...grpc.CallOption) (GoProxy_StreamHTTPClient, error)
	AnalyseURL(ctx context.Context, in *ModuleInfoRequest, opts ...grpc.CallOption) (*ModuleInfo, error)
	// given a path, will download response
	GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (GoProxy_GetPathClient, error)
}

type goProxyClient struct {
	cc *grpc.ClientConn
}

func NewGoProxyClient(cc *grpc.ClientConn) GoProxyClient {
	return &goProxyClient{cc}
}

func (c *goProxyClient) StreamHTTP(ctx context.Context, in *h2gproxy.StreamRequest, opts ...grpc.CallOption) (GoProxy_StreamHTTPClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GoProxy_serviceDesc.Streams[0], c.cc, "/goproxy.GoProxy/StreamHTTP", opts...)
	if err != nil {
		return nil, err
	}
	x := &goProxyStreamHTTPClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GoProxy_StreamHTTPClient interface {
	Recv() (*h2gproxy.StreamDataResponse, error)
	grpc.ClientStream
}

type goProxyStreamHTTPClient struct {
	grpc.ClientStream
}

func (x *goProxyStreamHTTPClient) Recv() (*h2gproxy.StreamDataResponse, error) {
	m := new(h2gproxy.StreamDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *goProxyClient) AnalyseURL(ctx context.Context, in *ModuleInfoRequest, opts ...grpc.CallOption) (*ModuleInfo, error) {
	out := new(ModuleInfo)
	err := grpc.Invoke(ctx, "/goproxy.GoProxy/AnalyseURL", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goProxyClient) GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (GoProxy_GetPathClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GoProxy_serviceDesc.Streams[1], c.cc, "/goproxy.GoProxy/GetPath", opts...)
	if err != nil {
		return nil, err
	}
	x := &goProxyGetPathClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GoProxy_GetPathClient interface {
	Recv() (*BinData, error)
	grpc.ClientStream
}

type goProxyGetPathClient struct {
	grpc.ClientStream
}

func (x *goProxyGetPathClient) Recv() (*BinData, error) {
	m := new(BinData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GoProxy service

type GoProxyServer interface {
	// h2gproxy endpoint
	StreamHTTP(*h2gproxy.StreamRequest, GoProxy_StreamHTTPServer) error
	AnalyseURL(context.Context, *ModuleInfoRequest) (*ModuleInfo, error)
	// given a path, will download response
	GetPath(*GetPathRequest, GoProxy_GetPathServer) error
}

func RegisterGoProxyServer(s *grpc.Server, srv GoProxyServer) {
	s.RegisterService(&_GoProxy_serviceDesc, srv)
}

func _GoProxy_StreamHTTP_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(h2gproxy.StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoProxyServer).StreamHTTP(m, &goProxyStreamHTTPServer{stream})
}

type GoProxy_StreamHTTPServer interface {
	Send(*h2gproxy.StreamDataResponse) error
	grpc.ServerStream
}

type goProxyStreamHTTPServer struct {
	grpc.ServerStream
}

func (x *goProxyStreamHTTPServer) Send(m *h2gproxy.StreamDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GoProxy_AnalyseURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoProxyServer).AnalyseURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goproxy.GoProxy/AnalyseURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoProxyServer).AnalyseURL(ctx, req.(*ModuleInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoProxy_GetPath_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPathRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoProxyServer).GetPath(m, &goProxyGetPathServer{stream})
}

type GoProxy_GetPathServer interface {
	Send(*BinData) error
	grpc.ServerStream
}

type goProxyGetPathServer struct {
	grpc.ServerStream
}

func (x *goProxyGetPathServer) Send(m *BinData) error {
	return x.ServerStream.SendMsg(m)
}

var _GoProxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goproxy.GoProxy",
	HandlerType: (*GoProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyseURL",
			Handler:    _GoProxy_AnalyseURL_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHTTP",
			Handler:       _GoProxy_StreamHTTP_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPath",
			Handler:       _GoProxy_GetPath_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/golang.conradwood.net/apis/goproxy/goproxy.proto",
}

// Client API for GoProxyTestRunner service

type GoProxyTestRunnerClient interface {
	Trigger(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*common.Void, error)
}

type goProxyTestRunnerClient struct {
	cc *grpc.ClientConn
}

func NewGoProxyTestRunnerClient(cc *grpc.ClientConn) GoProxyTestRunnerClient {
	return &goProxyTestRunnerClient{cc}
}

func (c *goProxyTestRunnerClient) Trigger(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/goproxy.GoProxyTestRunner/Trigger", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GoProxyTestRunner service

type GoProxyTestRunnerServer interface {
	Trigger(context.Context, *common.Void) (*common.Void, error)
}

func RegisterGoProxyTestRunnerServer(s *grpc.Server, srv GoProxyTestRunnerServer) {
	s.RegisterService(&_GoProxyTestRunner_serviceDesc, srv)
}

func _GoProxyTestRunner_Trigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoProxyTestRunnerServer).Trigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goproxy.GoProxyTestRunner/Trigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoProxyTestRunnerServer).Trigger(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoProxyTestRunner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goproxy.GoProxyTestRunner",
	HandlerType: (*GoProxyTestRunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Trigger",
			Handler:    _GoProxyTestRunner_Trigger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/golang.conradwood.net/apis/goproxy/goproxy.proto",
}

func init() {
	proto.RegisterFile("protos/golang.conradwood.net/apis/goproxy/goproxy.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 851 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x55, 0x5f, 0x8f, 0x1a, 0x37,
	0x10, 0xef, 0x02, 0x77, 0x1c, 0x03, 0x9c, 0x38, 0x27, 0x4a, 0x56, 0x34, 0xad, 0xd0, 0xaa, 0x91,
	0x4e, 0x7d, 0x20, 0x11, 0xa9, 0x5a, 0xa9, 0x52, 0x1f, 0xf8, 0x97, 0xcb, 0x29, 0x1c, 0xac, 0x7c,
	0x4b, 0x9a, 0xeb, 0x9b, 0xcb, 0x0e, 0xb0, 0x2a, 0xd8, 0xd4, 0x36, 0xcd, 0xf1, 0x21, 0xfa, 0xa5,
	0xfa, 0xd2, 0x6f, 0xd3, 0xcf, 0x50, 0xd9, 0xeb, 0x5d, 0xf6, 0xd2, 0x28, 0x7d, 0xf2, 0xfc, 0x7e,
	0xf3, 0xf3, 0xcc, 0x78, 0xc6, 0xeb, 0x85, 0x1f, 0x76, 0x52, 0x68, 0xa1, 0x5e, 0xac, 0xc4, 0x86,
	0xf1, 0x55, 0x77, 0x21, 0xb8, 0x64, 0xf1, 0x07, 0x21, 0xe2, 0x2e, 0x47, 0xfd, 0x82, 0xed, 0x12,
	0xe3, 0xda, 0x49, 0x71, 0x7f, 0xc8, 0xd6, 0xae, 0xdd, 0x41, 0xaa, 0x0e, 0xb6, 0xbb, 0x9f, 0xd9,
	0xba, 0x10, 0xdb, 0xad, 0xe0, 0x6e, 0x49, 0x37, 0xb6, 0x7b, 0x9f, 0xd1, 0xaf, 0x7b, 0xab, 0x34,
	0x57, 0x66, 0xa4, 0x7b, 0x82, 0xbf, 0x3c, 0x38, 0x1d, 0x0a, 0xbe, 0x4c, 0x56, 0xe4, 0x6b, 0x80,
	0x89, 0x58, 0xb0, 0xcd, 0x1b, 0xa1, 0xb4, 0xf2, 0xbd, 0x4e, 0xf9, 0xb2, 0x46, 0x0b, 0x0c, 0x19,
	0xc0, 0x45, 0x5f, 0x6a, 0x5c, 0xb2, 0x85, 0xa6, 0xa8, 0xc4, 0xe6, 0x0f, 0x94, 0xca, 0x2f, 0x75,
	0xca, 0x97, 0xf5, 0xde, 0xe3, 0x6e, 0x76, 0x84, 0x4c, 0x31, 0xc2, 0x25, 0xfd, 0xaf, 0xdc, 0xe4,
	0xb8, 0x12, 0x57, 0xa8, 0x43, 0x23, 0xf6, 0xcb, 0x1d, 0xcf, 0xe4, 0x38, 0x32, 0xe4, 0x3b, 0xa8,
	0x5d, 0x09, 0x63, 0x26, 0xa8, 0xfc, 0x8a, 0x8d, 0xfd, 0x24, 0x8f, 0x3d, 0xdf, 0xdd, 0x6a, 0x89,
	0x6c, 0x6b, 0xa5, 0xf4, 0x28, 0x0c, 0xfe, 0xf4, 0xa0, 0xf9, 0xc0, 0x49, 0x7c, 0xa8, 0xde, 0x30,
	0xbd, 0x58, 0xa3, 0xf4, 0x3d, 0x9b, 0x24, 0x83, 0xe4, 0x31, 0x9c, 0xa4, 0xc9, 0x4b, 0x96, 0x4f,
	0x01, 0x69, 0xc3, 0xd9, 0x5c, 0xa1, 0xe4, 0x6c, 0x8b, 0xae, 0xaa, 0x1c, 0x1b, 0x5f, 0xc8, 0x94,
	0xfa, 0x20, 0x64, 0xec, 0x57, 0x52, 0x5f, 0x86, 0x4d, 0xb4, 0x48, 0xfc, 0x86, 0xdc, 0x3f, 0x49,
	0xa3, 0x59, 0x10, 0x6c, 0xa1, 0x5e, 0xe8, 0x03, 0x21, 0x50, 0x09, 0x99, 0x5e, 0xbb, 0x4a, 0xac,
	0x6d, 0x1a, 0x91, 0x49, 0xae, 0x47, 0xb6, 0x96, 0x0a, 0x2d, 0x30, 0xe4, 0x09, 0x9c, 0x8e, 0xc4,
	0x96, 0x25, 0xdc, 0x95, 0xe3, 0x90, 0x89, 0x35, 0x35, 0x45, 0xa6, 0x85, 0x58, 0x3b, 0xf8, 0xa7,
	0x04, 0x8d, 0x21, 0x5b, 0xac, 0x31, 0xbe, 0x11, 0xf1, 0x7e, 0x83, 0xe4, 0x1c, 0x4a, 0xd7, 0x23,
	0x9b, 0xae, 0x42, 0x4b, 0xd7, 0xa3, 0xbc, 0x80, 0x52, 0xa1, 0x00, 0x1f, 0xaa, 0xef, 0x50, 0xaa,
	0x44, 0x64, 0x19, 0x32, 0x68, 0x52, 0xdf, 0xee, 0x97, 0xcb, 0xe4, 0xde, 0x25, 0x71, 0x88, 0xb4,
	0xa0, 0xfc, 0x16, 0x0f, 0xee, 0xa4, 0xc6, 0x34, 0x31, 0x86, 0x12, 0x99, 0xc6, 0xd8, 0x3f, 0xed,
	0x78, 0x97, 0x4d, 0x9a, 0x41, 0xd3, 0xb3, 0x09, 0x53, 0x7a, 0xae, 0x30, 0xf6, 0xab, 0xd6, 0x95,
	0x63, 0xd2, 0x81, 0x7a, 0x24, 0x06, 0x38, 0xc2, 0x0d, 0x9a, 0x9d, 0x67, 0x1d, 0xef, 0xf2, 0x8c,
	0x16, 0x29, 0x12, 0x40, 0xe3, 0x35, 0x4b, 0x36, 0x09, 0x5f, 0xdd, 0x26, 0x7c, 0x81, 0x7e, 0xcd,
	0x46, 0x78, 0xc0, 0x99, 0x28, 0x06, 0x0f, 0xc5, 0x9e, 0x6b, 0x94, 0x3e, 0x58, 0x49, 0x91, 0xb2,
	0xf7, 0x99, 0x29, 0x6d, 0x28, 0x8c, 0xfd, 0xba, 0x15, 0x14, 0x18, 0xf2, 0x0c, 0x6a, 0xe1, 0x3e,
	0x73, 0x37, 0x6c, 0x15, 0x47, 0xc2, 0x4e, 0x7d, 0xaf, 0xc7, 0x52, 0x0a, 0xe9, 0x37, 0xdd, 0xd4,
	0x1d, 0x0e, 0x9e, 0xc3, 0x45, 0xda, 0xe9, 0x6b, 0xbe, 0x14, 0x14, 0x7f, 0xdf, 0xa3, 0xd2, 0xa6,
	0x3d, 0x73, 0x3a, 0x71, 0x43, 0x36, 0x66, 0x70, 0x07, 0x70, 0x94, 0x91, 0x57, 0x19, 0x8a, 0x0e,
	0x3b, 0xb4, 0xb2, 0xf3, 0xde, 0xa3, 0xfc, 0x6e, 0xdf, 0xcc, 0x46, 0xf3, 0xc9, 0x38, 0xba, 0x0b,
	0xc7, 0xb4, 0x20, 0x33, 0xb3, 0x18, 0xdf, 0x27, 0xe6, 0x7b, 0x2c, 0xd9, 0x02, 0x1d, 0x0a, 0x56,
	0x50, 0x77, 0xe3, 0xb2, 0xb1, 0x0b, 0xc3, 0x4c, 0xa7, 0x9e, 0x0f, 0xf3, 0x19, 0xd4, 0x06, 0xfb,
	0x64, 0x13, 0x47, 0xc9, 0x16, 0x6d, 0x8c, 0x26, 0x3d, 0x12, 0xa6, 0x89, 0x4e, 0x38, 0x3d, 0xde,
	0xfc, 0x22, 0x15, 0x7c, 0x03, 0xe7, 0xe6, 0xe3, 0x64, 0x7a, 0x9d, 0x9d, 0xf3, 0x13, 0xb7, 0x39,
	0xf8, 0x0a, 0xaa, 0x83, 0x84, 0x8f, 0x98, 0x66, 0xc6, 0x6d, 0x56, 0xeb, 0x6e, 0x50, 0x6b, 0x7f,
	0x6b, 0x1a, 0x91, 0x9f, 0x8f, 0xd4, 0xa1, 0x3a, 0x9f, 0xbe, 0x9d, 0xce, 0x7e, 0x9e, 0xb6, 0xbe,
	0x20, 0x35, 0x38, 0x09, 0xe9, 0x2c, 0x9a, 0xb5, 0x4a, 0xa4, 0x01, 0x67, 0x7d, 0x1a, 0x8d, 0x5f,
	0xf7, 0x87, 0x51, 0xab, 0x4c, 0x08, 0x9c, 0x8f, 0xdf, 0x47, 0x63, 0x3a, 0xed, 0x4f, 0xd2, 0xbd,
	0xad, 0x0a, 0xb9, 0x80, 0xe6, 0x3c, 0xbc, 0x8d, 0xe8, 0xb8, 0x7f, 0x13, 0xd2, 0xd9, 0xfb, 0xbb,
	0xd6, 0x49, 0xef, 0x6f, 0x0f, 0xaa, 0xe9, 0x43, 0x70, 0x20, 0x63, 0x80, 0xf4, 0x0d, 0x78, 0x13,
	0x45, 0x21, 0x79, 0xda, 0xcd, 0x9f, 0xba, 0x94, 0x75, 0x07, 0x68, 0x3f, 0xfb, 0xd8, 0x61, 0x6a,
	0xa4, 0xa8, 0x76, 0x82, 0x2b, 0x7c, 0xe9, 0x91, 0x9f, 0x00, 0xfa, 0x9c, 0x6d, 0x0e, 0x0a, 0xe7,
	0x74, 0x42, 0xda, 0xc7, 0x11, 0x7d, 0x3c, 0xf2, 0xf6, 0xa3, 0x4f, 0xf8, 0xc8, 0xf7, 0x50, 0x75,
	0x1d, 0x23, 0x4f, 0x73, 0xff, 0xc3, 0x1e, 0xb6, 0x5b, 0xb9, 0xc3, 0xb5, 0xed, 0xa5, 0xd7, 0xfb,
	0x11, 0x2e, 0xdc, 0x41, 0x22, 0x54, 0x9a, 0xee, 0x39, 0x47, 0x49, 0x9e, 0x43, 0x35, 0x92, 0xc9,
	0x6a, 0x85, 0x92, 0x34, 0xba, 0xee, 0xb1, 0x7f, 0x27, 0x92, 0xb8, 0xfd, 0x00, 0x0d, 0xfa, 0xf0,
	0x25, 0x47, 0x5d, 0x7c, 0xf8, 0xcd, 0xa3, 0x9f, 0x25, 0xf9, 0x25, 0xf8, 0xff, 0x7f, 0xd0, 0xaf,
	0xa7, 0xf6, 0x7f, 0xf0, 0xea, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0xff, 0xaa, 0x2a, 0xb7,
	0x06, 0x00, 0x00,
}
