package proto

import (
	"archive/zip"
	"context"
	"flag"
	"fmt"
	"golang.conradwood.net/apis/common"
	gom "golang.conradwood.net/apis/gomodule"
	pb "golang.conradwood.net/apis/goproxy"
	pr "golang.conradwood.net/apis/protorenderer"
	//	"golang.conradwood.net/go-easyops/errors"
	"golang.conradwood.net/goproxy/cacher"
	hh "golang.conradwood.net/goproxy/handlerhelpers"
	"io"
	"strings"
)

var (
	cache_mod                = flag.Bool("cache_go_mod_proto", false, "if true also cache the go.mod file from protos. Should not be necessary because it is autogenerated")
	use_gomodule_to_serve    = flag.Bool("use_gomodule_to_serve_proto_zips", true, "if true, we serve all proto zip files from gomodule")
	debug                    = flag.Bool("debug_proto", false, "debug proto stuff")
	WELL_KNOWN_PATH_PREFIXES = []string{
		"golang.conradwood.net/apis",
		"golang.singingcat.net/apis",
		"golang.yacloud.eu/apis",
	}
)

type protoHandler struct {
	pack    *pr.Package
	version *pr.Version
	path    string
	modname string
}

func HandlerByPath(ctx context.Context, path string) (*protoHandler, error) {
	pn := &pr.PackageName{PackageName: path}
	pack, err := pr.GetProtoRendererClient().GetPackageByName(ctx, pn)
	if err != nil {
		if *debug {
			fmt.Printf("No proto package for path \"%s\": %s\n", path, err)
		}
		if isWellKnownProtoPath(path) {
			// we know user means us (path matches a proto path), but it's wrong
			return &protoHandler{}, nil
		}
		return nil, nil
	}
	p := &protoHandler{pack: pack, path: path}
	p.version, err = pr.GetProtoRendererClient().GetVersion(ctx, &common.Void{})
	p.modname = path
	return p, nil
}
func (ph *protoHandler) ModuleInfo() *pb.ModuleInfo {
	res := &pb.ModuleInfo{ModuleType: pb.MODULETYPE_PROTO}
	if ph.pack != nil {
		res.Exists = true
	}
	return res
}
func (ph *protoHandler) ListVersions(ctx context.Context) ([]*pb.VersionInfo, error) {
	if ph.pack == nil {
		return nil, nil
	}
	vi := &pb.VersionInfo{Version: ph.version.Version}
	return []*pb.VersionInfo{vi}, nil
}
func isWellKnownProtoPath(path string) bool {
	for _, s := range WELL_KNOWN_PATH_PREFIXES {
		if strings.HasPrefix(path, s) {
			return true
		}
	}
	return false
}
func (ph *protoHandler) GetLatestVersion(ctx context.Context) (*pb.VersionInfo, error) {
	vi := &pb.VersionInfo{Version: ph.version.Version}
	return vi, nil
}

func (ph *protoHandler) GetZip(ctx context.Context, c *cacher.Cache, w io.Writer, version string) error {
	if *use_gomodule_to_serve {
		pr := &gom.ProtoRequest{
			PackageName: ph.path,
			Version:     version,
		}
		srv, err := gom.GetGoModuleClient().GetProtoZip(ctx, pr)
		if err != nil {
			return err
		}
		for {
			r, err := srv.Recv()
			if err != nil {
				if err == io.EOF {
					break
				}
				return err
			}
			_, err = w.Write(r.Data)
			if err != nil {
				return err
			}
		}
		return nil
	}
	vid, err := hh.ParseIDFromString(version)
	if err != nil {
		return err
	}
	//	fmt.Printf("Getting proto zip for package \"%s\", version \"%d\"\n", ph.pack.Name, ph.version.Version)
	fmt.Printf("Requested version: \"%d\", current version: \"%d\"\n", vid, ph.version.Version)

	// don't enforce version. instead we rely on caches (otherwise we are unable to build the cache)
	/*
		if ph.version.Version != vid {
			s := fmt.Sprintf("proto in version %d is not available (current version is %d)", vid, ph.version.Version)
			return errors.InvalidArgs(ctx, s, s)
		}
	*/

	pn := &pr.PackageName{PackageName: ph.modname}
	srv, err := pr.GetProtoRendererClient().GetFilesGoByPackageName(ctx, pn)
	if err != nil {
		return err
	}
	zw := zip.NewWriter(w)

	/*
		// now add go.mod
		modfile, err := ph.GetMod(ctx, version)
		if err != nil {
			return err
		}
		modwriter, err := zw.Create(hh.Filename2ZipFilename(ph.modname, version, "go.mod"))
		if err != nil {
			return err
		}
		_, err = modwriter.Write(modfile)
		if err != nil {
			return err
		}
	*/
	// now add the files
	lastfile := ""
	var curwriter io.Writer
	for {
		zf, err := srv.Recv()
		if err != nil {
			fmt.Printf("Err:%s\n", err)
			if err == io.EOF {
				break
			}
			return err
		}
		//		fmt.Printf("Gofile received: %s (%d bytes)\n", zf.Filename, len(zf.Payload))
		if lastfile != zf.Filename && zf.Filename != "" {
			lastfile = zf.Filename
			curwriter, err = zw.Create(hh.Filename2ZipFilename(ph.modname, version, zf.Filename))
			if err != nil {
				return err
			}
		}
		if len(zf.Payload) > 0 {
			_, err = curwriter.Write(zf.Payload)
			if err != nil {
				return err
			}
		}
	}
	err = zw.Close()
	if err != nil {
		return err
	}

	return nil
}
func (ph *protoHandler) GetMod(ctx context.Context, c *cacher.Cache, version string) ([]byte, error) {
	res := "module " + ph.path
	buf := []byte(res)
	if *cache_mod {
		c, err := cacher.NewCacher(ctx, ph.path, version, "mod")
		if err != nil {
			return nil, err
		}
		err = c.PutBytes(ctx, buf)
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}
func (af *protoHandler) CacheEnabled() bool {
	return true
}
